services:
  tei:
    build:
      context: ./apis
      dockerfile: TEI-Dockerfile
    image: tei:local
    ports:
      - "10000:10000"
    networks:
      - cafecito-net

  beansapi:
    build:
      context: ./apis
      dockerfile: beans/Dockerfile
    image: beans-api:local
    ports:
      - "8080:8080"
    volumes:
      - ./apis/beans/.beansack:/app/data
    environment:
      PORT: "8080"
      EMBEDDER_BASE_URL: tei:10000
    env_file:
      - ./apis/beans/.env
    depends_on:
      - tei
    networks:
      - cafecito-net

  espressoapi:
    build:
      context: ./apis
      dockerfile: espresso/Dockerfile
    image: espresso-api:local
    ports:
      - "8081:8080"
    environment:
      PORT: "8080"
      EMBEDDER_BASE_URL: tei:10000
    env_file:
      - ./apis/espresso/.env
    depends_on:
      - tei
    networks:
      - cafecito-net

networks:
  cafecito-net:
    driver: bridge
