services:
  beansapi:
    build:
      context: ./apis
      dockerfile: Dockerfile
      args:
        SERVICE: beans
    image: beans-api:local
    ports:
      - "8080:8080"
    env_file:
      - ./apis/beans/.env
    networks:
      - cafecito-net

  espressoapi:
    build:
      context: ./apis
      dockerfile: Dockerfile
      args:
        SERVICE: espresso
    image: espresso-api:local
    ports:
      - "8081:8080"
    env_file:
      - ./apis/espresso/.env
    networks:
      - cafecito-net

networks:
  cafecito-net:
    driver: bridge
