app = "cafecito-embedder-api"

[build]
  dockerfile = "Dockerfile.embedder"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0  

[[vm]]
  size = 'shared-cpu-4x'
  memory = '2gb'