name: Prod
variables:
  - name: baseUrl
    value: https://api.cafecito.tech/beans
    description: ""
  - secret: true
    name: apiKey
    description: Create an api key from https://developer.cafecito.tech/settings/api-keys
